# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

before_test:
  - choco install miktex
  - choco install pandoc
  - ps: $env:Path += ";C:\Program Files\MiKTeX 2.9\miktex\bin\x64\"
  - pdflatex -version

test_script:
  - Rscript -e "rmarkdown::render('report.Rmd')"

  - path: 'report.pdf'
    name: Report
